[profile.default]
src = 'contracts'
out = 'out'
viaIR = true
libs = ['node_modules', 'lib']
test = 'test'
cache_path  = 'cache_forge'
verbosity = 3
fs_permissions = [{ access = "read", path = "./node_modules" }]

[dependencies]
forge-std = "1.9.2"
